### ISSUE TITLE
Warrior Bot battle shout bug

### ISSUE THREAD

**Issue by GabrielFranchini96** [SoloCraftServer/bugtracker#153]
## 🐛 Bug report
When spawning a warrior tank bot, it uses a low-rank Battle Shout
![image](https://github.com/SoloCraftServer/bugtracker/assets/44416710/90ac4193-1553-4d89-987c-8d3ef30a0cec)
If the spawned bot is a DPS warrior, the rank seems to be higher/proper for level
![image](https://github.com/SoloCraftServer/bugtracker/assets/44416710/b2186fdf-7ffb-4b6a-8858-3fcc1ad91a17)

### Steps to reproduce
1. Spawn warrior tank bot
2. Make sure you're dismounted so that the bot applies buffs on spawn
3. Mouseover the Battle Shout buff to check how much Attack Power is provided

**Comment by SoloCraftServer** [comment]
Lower level bots will now correctly learn all skills from the trainer itself once they are spawned
they were using a premade template before, and since they auto learn random talent specs according to their role, they were using sometimes lower rank buffs etc. This update will fix other low lvl bot classes aswell in case they were using lower rank spells
