### ISSUE TITLE
Caster have to use wand instead of auto attack

### ISSUE THREAD

**Issue by Altair484** [SoloCraftServer/bugtracker#26]
## 🐛 Bug report
Remove mage auto attack melee order when they start dps. Prefer wand dps instead. Using melee attack leads mages/warlock to melee and it can be deadly in pve or raids.

At the moment when they use spells that are instant, during the gdc they march towards the target

### Expected behavior
Casters should use wand. I hope that way they will stand back in range position.

**Comment by SoloCraftServer** [comment]
Casters do use wands once their mana is below 5%.  

If the range between the caster and target is too close, they will run closer to cast low range spells before they cast high range spells such as frostbolt. 

Also since we've disabled "run-away-from-target" to prevent unwanted pulls/aggro, they won't run away once they are too close to the target.  Just make sure there is enough range. :)

**Comment by Altair484** [comment]
Ok so it means that because [fire blast](https://www.wowhead.com/classic/spell=10199/fire-blast) is 20 yards range my mages cant dps at max range, same for hunters coming at scatter shot range. It is a problem for many boss fights like shazzrah :/ I cant get my mages avoid the arcane explosion, even if i tell them to come to me at 30yards they keep returning at 20 yards. Your explanation why they do that makes sense for me now, but it should be avoidable, mostly in raids, can you do that ? I know you did some specific bots behaviour for raids only, like decurses or dispel magic update :) thanks for that, i hope getting a response here even if the report is closed...
